name = "moonshot-proxy"
version = "0.1.0"
component = "./target/wasm32-wasip1/release/moonshot_proxy.wasm"
init_state = "./init-moonshot.json"

[[handler]]
type = "runtime"

[[handler]]
type = "environment"
allow_list_all = false

[[handler]]
type = "timing"
max_sleep_duration = 3600000
min_sleep_duration = 1

[[handler]]
type = "http-client"

[[handler]]
type = "message-server"
